import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import Feed from "../components/Feed"
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>insta-clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icons/icons8-instagram.svg"/>
        <link rel="icon" href="/icons/icons8-instagram.svg" />
      </Head>

      {/* Header */}
      <Header />

      <Feed />

      {/* Modal */}
    </>
  );
}
